# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "github-pages", "~> 214", group: :jekyll_plugins

gem "webrick", "~> 1.7"
